z = {'$ingapore': 'singapore',
'10 char': '10 characters',
'10kkj': 'Tampines',
'10penis': 'Tampines',
'10q': 'thank you',
'12': 'want to',
'121': 'one to one',
'143': 'i love you',
'1ab': 'wanna be',
'1daful': 'wonderful',
'1dering': 'wondering',
'1nce': 'once',
'1sec': 'one second',
'1z': 'once',
'22': 'tutu',
'24/7': 'all the time',
'2b': 'to be',
'2b4u': 'too bad for you',
'2b@': 'to be at',
'2bad4u2': 'too bad for you too',
'2bh': 'to be honest',
'2c4u': 'too cool for you',
'2d4': 'to die for',
'2da': 'to the',
'2dae': 'today',
'2day': 'today',
'2dfm': 'too dumb for me',
'2ditd': 'today is the day',
'2ez': 'too easy',
'2fb': 'too freaking bad',
'2g2b4g': 'too good to be forgotten',
'2g2bt': 'too good to be true',
'2getha': 'together',
'2gether': 'together',
'2getr': 'together',
'2gthr': 'together',
'2h2h': 'too hot to handle',
'2l8': 'too late',
'2m': 'tomorrow',
'2m4u': 'too much for you',
'2ma': 'tomorrow',
'2maro': 'tomorrow',
'2mmrw': 'tomorrow',
'2mo': 'tomorrow',
'2mora': 'tomorrow',
'2moro': 'tomorrow',
'2morow': 'tomorrow',
'2morro': 'tomorrow',
'2morrow': 'tomorrow',
'2moz': 'tomorrow',
'2mr': 'tomorrow',
'2mro': 'tomorrow',
'2night': 'tonight',
'2nite': 'tonight',
'2nte': 'tonight',
'2nyt': 'tonight',
'2qt': 'too cute',
'2sday': 'tuesday',
'2tali': 'totally',
'2tm': 'to the max',
'2trd': 'too tired',
'2u2': 'to you too',
'458': 'i love you',
'4col': 'for crying out loud',
'4eae': 'forever and ever',
'4eva': 'forever',
'4ever': 'forever',
'4g8': 'forget',
'4gai': 'forget about it',
'4geit': 'forget it',
'4get': 'forget',
'4n': 'foreign',
'4nr': 'foreigner',
'4q': 'fuck you',
'4rl': 'for real',
'4ward': 'forward',
'5c': 'cash car credit card condominium country club',
'6c': 'Career Cash Car Credit card Condominium Country club',
'6y': 'sexy',
'9t': 'night',
'?': 'question',
'@@-o': 'tattletale',
'@teotd': 'at the end of the day',
'^5': 'high five',
'a/n': "author's note",
'a2d': 'agree to disagree',
'a3': 'anytime, any place, anywhere',
'aa': 'attract attention',
'aak': 'asleep at keyboard',
'aamof': 'as a matter of fact',
'aamoi': 'as a matter of interest',
'aar': 'at any rate',
'aar8': 'at any rate',
'aas': 'alive and smiling',
'aatk': 'always at the keyboard',
'aayf': 'as always, your friend',
'abbb': 'act big buay big',
'abg': 'abang',
'abnn': 'ah bu neh neh',
'abourit': 'about it',
'abt': 'about',
'abt2': 'about to',
'ac': 'air conditioner',
'acbc': 'act cool buay cool',
'acbckns': 'act cute buey cute kanasai',
'accmpny': 'accompany',
'acd': 'alt control delete',
'ack': 'acknowledgement',
'act bz': 'act busy',
'adad': 'another day another dollar',
'adbb': 'all done bye bye',
'addr': 'address',
'addy': 'address',
'adih': 'another day in hell',
'adip': 'another day in paradise',
'adpic': 'always dependably politically incorrect',
'adrs': 'address',
'advd': 'advised',
'aeap': 'as early as possible',
'af': 'as fuck',
'afagay': 'a friend as good as you',
'afaic': "as far as i'm concerned",
'afaics': 'as far as I can see',
'afaict': 'as far as I can tell',
'afaik': 'as far as I know',
'afair': 'as far as I remember',
'afaiu': 'as far as I understand',
'afaiui': 'as far as I understand it',
'afap': 'as far as possible',
'afayc': "as far as you're concerned",
'afbf': 'act funny buay funny',
'afc': 'away from computer',
'afda': 'a few days ago',
'afdb': 'a few days back',
'afiaa': 'as far as I am aware',
'afj': 'april fools joke',
'afk': 'away from keyboard',
'afpoe': 'a fresh pair of eyes',
'aft': 'about fucking time',
'afu': 'all fucked up',
'agl': 'angel',
'ah gua': 'transvestite',
'ah kwa': 'transvestite',
'ah qua': 'transvestite',
'ahfy': 'always here for you',
'ai': 'artificial intelligence',
'aiamu': "and i'm a monkey's uncle",
'aight': 'all right',
'aih': 'as it happens',
'aimb': 'as I mentioned before',
'air-kon': 'air-conditioner',
'air con': 'air conditioner',
'aisb': 'as I said before',
'aise': 'as I said earlier',
'aisi': 'as I see it',
'aitr': 'adult in the room',
'aj': 'a jay',
'ajzm': 'ai jiat zua mai',
'ak': 'ah kua',
'aka': 'also known as',
'akl': 'ah ka liau',
'alap': 'as late as possible',
'albl': 'act lian buay lian',
'alol': 'actually laughing out loud',
'alot': 'a lot',
'alotbsol': 'always look on the bright side of life',
'alt': 'alternative',
'altg': 'act locally, think globally',
'alw': "ain't life wonderful",
'ama': 'ask me anything',
'amap': 'as much as possible',
'ambw': 'all my best wishes',
'aml': 'all my love',
'an': 'ah neh',
'anfscd': 'and now for something completely different',
'angwee': 'angry',
'anot': 'or not',
'any1': 'anyone',
'aoas': 'all of a sudden',
'aomm': 'always on my mind',
'appm': 'want to have sex?',
'appt': 'appointments',
'appts': 'appointments',
'aq': 'ah kua',
'aqua': 'ah kua',
'arbr': 'act rich buay rich',
'ard': 'around',
'asafp': 'as soon as fucking possible',
'asaic': 'as soon as I can',
'asap': 'as soon as possible',
'asaygt': 'as soon as you get this',
'asbs': 'act sweet buay sweet',
'asf': 'as fuck',
'asgm': 'want to have sex?',
'asl': 'age, sex, location',
'aslmh': 'age, sex, location, music, hobbies',
'asp': 'after show party',
'asw': 'attention seeking whore',
'atab': "ain't that a bitch",
'atbd': 'ah tiong',
'atbt': 'act tall buay tall',
'atsl': 'along the same line',
'atst': 'at the same time',
'att': 'attend',
'attwaction': 'attraction',
'attwicted': 'addicted',
'atw': 'all the way',
'atwd': 'agree that we disagree',
'awhfy': 'are we having fun yet',
'awk': 'awkward',
'awol': 'absent',
'ay-jay': 'a jay',
'ayc': 'are you coming',
'ayce': 'all you can eat',
'ayk': 'as you know',
'aymm': 'are you my mother',
'aypi': 'and your point is?',
'aysos': 'are you stupid or something?',
'aytmtb': "and you're telling me this because",
'b&f': 'back and forth',
'b/c': 'because',
'b/w': 'between',
'b2a': 'business-to-anyone',
'b2b': 'business-to-business',
'b2b2c': 'business-to-business-to-consumer',
'b2c': 'business-to-consumer',
'b2d': 'business-to-distributor',
'b2e': 'business-to-employee',
'b2g': 'business-to-government',
'b3': 'blah, blah, blah',
'b4': 'before',
'b4n': 'bye for now',
'b4u': 'before you',
'b4yki': 'before you know it',
'b@': 'be at',
'b@u': 'back at you',
'bac': 'bad ass chick',
'badass': 'cool, confident person',
'bae': 'baby',
'baf': 'bring a friend',
'bak': 'back at keyboard',
'bak@u': 'back at you',
'bamf': 'bad ass motherfucker',
'bau': 'business as usual',
'bb': 'bye bye',
'bb4n': 'bye bye for now',
'bbb': 'boring beyond belief',
'bbbg': 'bye bye be good',
'bbfn': 'bye bye for now',
'bbiab': 'be back in a bit',
'bbiaf': 'be back in a few',
'bbias': 'be back in a second',
'bbiaw': 'be back in a while',
'bbl': 'be back later',
'bbm': 'broken back mountain',
'bbn': 'bye bye now',
'bbnu': 'millenials',
'bbq': 'barbeque',
'bbs': 'be back soon',
'bbt': 'be back tomorrow',
'bbw': 'be back whenever',
'bby': 'baby',
'bc': 'because',
'bcc': 'grumpy',
'bcf': 'braggart',
'bcnu': 'be seeing you',
'bcny': 'be seeing you',
'bco': 'big crush on',
'bcos': 'because',
'bcoy': 'big crush on you',
'bcoz': 'because',
'bd': 'big deal',
'bday': 'birthday',
'bdk payung': 'budak payung',
'bdw': 'by the way',
'bestie': 'best friend',
'bf': 'boyfriend',
'bff': 'best friend forever',
'bff4l': 'best friends forever for life',
'bffe': 'best friends forever',
'bffn': 'best friend for now',
'bfftte': 'best friends forever till the end',
'bfk': 'big fat kiss',
'bfn': 'bye for now',
'bftd': 'best friends till death',
'bfyki': 'before you know it',
'bg': 'be good',
'bgf': 'best friend',
'bgr': 'boy-girl relationship',
'bhb': 'buay hiao bai',
'bi': 'business intelligence',
'bi5': 'back in five',
'bibi': 'bye bye',
'biffles': 'best friends for life',
'bil': 'brother-in-law',
'bio': 'bring it on',
'bion': 'believe it or not',
'bitd': 'back in the day',
'bits': 'back in the saddle',
'bk': 'bun knife',
'bka': 'better known as',
'bling': 'overly flashy jewellery',
'blkbry': 'blackberry',
'blocker': 'block others',
'blzrd': 'blizzard',
'bm': 'byte me',
'bm&y': 'between me and you',
'bma': 'best mates always',
'bmf': 'bad mother fucker',
'bmgwl': 'busting my gut with laughter',
'bmw': 'bus MRT walk',
'bn': 'been',
'bno': "boys' night out",
'bon': 'believe it or not',
'bootsie': 'boring person',
'bout': 'about',
'boutta': 'about to',
'boyzillion': 'brazilian wax for guys',
'bps': 'buay paiseh',
'br': 'bathroom',
'brb': 'be right back',
'brics': 'brazil, russia, india, china, south africa',
'bridezilla': 'crazy bride',
'bro': 'brother',
'brt': 'be right there',
'bs': 'bullshit',
'bsod': 'blue screen of death',
'bt': 'bitorrent',
'bta': 'but then again',
'btd': 'bored to death',
'btdt': 'been there done that',
'btfl': 'beautiful',
'btfldy': 'beautiful day',
'bth': 'cannot stand it',
'btn': 'better than nothing',
'btr': 'better',
'btsoom': 'beats the shit out of me',
'btss': 'bian tai shu shu',
'btw': 'by the way',
'btwitily': 'by the way, I think I love you',
'btwn': 'between',
'buf': 'big, ugly, fat',
'bup': 'backup plan',
'bus3rd': 'bastard',
'buttseck': 'butt sex',
'buwee': 'bully',
'bwg': 'boh wei gong',
'bwl': 'bursting with laughter',
'bwtm': "but wait, there's more",
'byam': 'between you and me',
'byki': 'before you know it',
'bykt': 'but you knew that',
'byo': 'bring your own',
'bz': 'busy',
'c': 'see',
'c&g': 'chuckle and grin',
"c'mon": 'come on',
'c/s': 'change of subject',
'c3': 'control command communication',
'c4n': 'ciao for now',
'c hw': 'see how',
'c hw 1st': 'see how first',
'c wat': 'see what',
'c wat c': 'see what see',
'c ya': 'see you',
'caac': 'cool as a cucumber',
'cab': 'chao ah beng',
'cal': 'chao ah lian',
'cas': 'crack a smile',
'catfish': 'person assuming a false identity',
'cb': 'chee bye',
'cb leaf': 'chee bye leaf',
'cb mouth': 'chee bye mouth',
'cbb': 'explosion sound',
'cbf': "can't be fucked",
'cc': 'protect yourself',
'cca': 'Co-curricular activities',
'ccb': 'chao chee bye',
'cdfu': 'cracking the fuck up',
'cf': 'braggart',
'cfcm': 'cry father cry mother',
'cfm': 'confirm',
'cicyhw': 'can I copy your home work',
'cim': 'come in mouth',
'cklps': 'chui kong lum par song',
'ckp': 'pervert',
'cld': 'could',
'climb hill': 'climb bukit timah hill',
'clk': 'click',
'cm': 'come',
'cmb': 'call me back',
'cmi': 'cannot make it',
'cmiiw': "correct me if i'm wrong",
'cmiw': "correct me if i'm wrong",
'cmon': 'come on',
'cmu': 'crack me up',
'cn': 'can',
'cn die': 'can die',
'cnb': 'catch no ball',
'cnc': 'comments and criticism',
'cnfm': 'confirm',
'cny': 'chinese new year',
'co ok?': 'commanding officer ok?',
'col': 'crying out loud',
'comfy': 'comfortable',
'cos': 'cause',
'coz': 'cause',
'cpe': 'coolest person ever',
'cqrt': 'security',
'cr': 'chicken rice',
'crat': "can't remember a thing",
'crb': 'come right back',
'crbt': 'crying real big tears',
'cre8': 'create',
'creeper': 'a socially invasive person',
'crew': 'group of friends',
'crispy': 'inferiority or incompetence',
'crone': 'clone account',
'crtla': "can't remember the three letter acronym",
'cs': 'change of subject',
'csa': 'cool sweet awesome',
'csabr': 'continued success and best regards',
'csb': 'cool story bro',
'csi': 'investigate',
'csl': "can't stop laughing",
'csn': 'chuckle, snicker, grin',
'ctn': 'cannot talk now',
'cto': 'check this out',
'cu': 'see you',
'cu2mr': 'see you tomorrow',
'cu46': 'see you for sex',
'cul': 'see you later',
'cul8r': 'see you later',
'cula': 'see you later alligator',
'cuns': 'see you in school',
'cuol': 'see you online',
'cupl': 'couple',
'cus': 'see you soon',
'cuz': 'cause',
'cwot': 'complete waste of time',
'cwyl': 'chat with you later',
'cy': 'calm yourself',
'cyal8r': 'see you later',
'cye': 'check your email',
'cyf': 'cross your fingers',
'cyfb': 'check your facebook',
'cyl': 'see you later',
'cym': 'check your mail',
'cyo': 'see you online',
'cyoh': 'create your own happening',
'cyol': 'see you online',
'cyt': 'see you tomorrow',
'd': 'the',
'd&d': 'dinner and dance',
'd&m': 'deep and meaningful',
'd/c': 'disconnected',
'd00d': 'dude',
'd2d': 'day-to-day',
'd8': 'date',
'da': 'the',
'dafuq': 'the fuck',
'dat': 'that',
'dayum': 'damn',
'db': 'detention barracks',
'dbabai': "don't be a bitch about it",
'dbd': "don't be dumb",
'dbeyr': "don't believe everything you read",
'dbf': 'dragon boat festival',
'dbmib': "don't bother me i'm busy",
'dbts': "don't believe that stuff",
'dc': 'daycare',
'dcp': 'daughter of very rich men',
'dcs': 'die cock stand',
'dd': 'dear daughter',
'ddas': "don't do anything stupid",
'ddg': 'drop dead gorgeous',
'ddsos': 'different day, same old shit',
'ddwi': "don't dick with it",
'deets': 'details',
'def': 'definitely',
'degt': "don't even go there",
'dem': 'them',
'den': 'then',
'dese': 'these',
'deti': "don't even think it",
'detweet': 'delete tweet',
'dewd': 'dude',
'dey': 'they',
'df': 'dear friend',
'dfik': 'darn if I know',
'dftba': "don't forget to be awesome",
'dgaf': "don't give a fuck",
'dgt': "don't go there",
'dgyf': "damn girl, you're fine",
'dh': 'dear husband',
'dhyb': "don't hold your breath",
'dic': 'drunk in charge',
'diku': 'do I know you?',
'diky': 'do I know you?',
'dil': 'daughter-in-law',
'dilligad': 'do I look like I give a damn',
'dilligaff': 'does it look like I give a flying flip',
'dilligas': 'do I look like I give a shit?',
'dinr': 'dinner',
'dip dip': 'deep deep',
'dis': 'this',
'disto': 'did I say that out loud?',
'ditg': 'down in the gutter',
'ditr': 'dancing in the rain',
'diy': 'do it yourself',
'djm': "don't judge me",
'dk': "don't know",
'dkdc': "don't know don't care",
'dl': 'doing laundry',
'dltm': "don't lie to me",
'dm': 'direct message',
'dmi': "don't mention it",
'dmy': "don't mess yourself",
'dnb': 'big bosom woman',
'dnbl8': 'do not be late',
'dnn': 'big neh neh',
'doin': 'doing',
"don'ch": "don't",
"don'ch shy": "don't be shy",
"don'mention": "don't mention it",
'dono': 'don’t know',
'dp': 'display picture',
'ds': 'dear son',
'dta': "don't trust anyone",
'dtf': 'down to fuck',
'dtrt': 'do the right thing',
'du': 'darn you',
'dubdew': 'pronuntiation of w',
'duct': 'did you see that',
'duk': "didn't you know",
'dun': "don't",
'dunno': "don't know",
'durs': 'damn you are sexy',
'dw': "don't worry",
'dw2h': "don't work too hard",
'dwb': "don't write back",
'dwbh': "don't worry be happy",
'dweet': 'drunk tweet',
'dwh': 'during work hours',
'dwn': 'down',
'dy': 'day',
'dyac': 'damn you auto-correct',
'dyd': "don't you dare",
'dyfm': 'dude you fascinate me',
'dyhab': 'do you have a boyfriend?',
'dyhag': 'do you have a girlfriend?',
'dyk': 'did you know?',
'dyli': 'do you love it?',
'e1': 'everyone',
'e123': 'easy as 1, 2, 3',
'e2ho': 'each to his own',
'eak': 'eating at keyboard',
'eavestweeting': 'eavesdropping on twitter conversations',
'edmw': 'eat drink man woman forum',
'eg': 'evil grin',
'el': 'evil laugh',
'elol': 'evil laugh out loud',
'engrand': 'england',
'enuf': 'enough',
'eod': 'end of discussion',
'eor': 'end of rant',
'epik phail': 'epic fail',
'ermahgerd': 'oh my gosh',
'essciting': 'exciting',
'essploded': 'exploded',
'every1': 'everyone',
'evre1': 'every one',
'ey': 'hey',
'eyc': 'excited yet calm',
'ez': 'easy',
'f': 'female',
'f/u': 'follow up',
'f2f': 'face to face',
'f9': 'fine',
'facepalm': 'ugh, idiot',
'facestalking': 'stalking on facebook',
'faf': 'funny as fluff',
'fap': 'onomatopoeic for male masturbation',
'faq': 'frequently asked questions',
'fav': 'favorite',
'fave': 'favorite',
'favs': 'favorites',
'fawc': 'for anyone who cares',
'fb': 'facebook',
'fbc': 'facebook chat',
'fbf': 'facebook friend',
'fc': 'fingers crossed',
'fcfs': 'first come, first served',
'fckin': 'fucking',
'fcol': 'for crying out loud',
'fcp': 'fake cheese pie',
'feels': 'feelings',
'ffk': 'stand someone up',
'ffs': "for fuck's sake",
'fh': 'future husband',
'fho': 'friends hanging out',
'fifo': 'first in, first out',
'fil': 'father-in-law',
'fl': 'freelancer',
'fml': 'fuck my life',
'foaf': 'friend of a friend',
'foc': 'free of charge',
'fofl': 'falling on floor laughing',
'fogc': 'fear of getting caught',
'foh': 'fuck out of here',
'fomo': 'fear of missing out',
'foodie': 'food enthusiast',
'forazumper': 'for example',
'fos': 'full of shit',
'fouo': 'for official use only',
'fr': 'for real',
'fre-end': 'buddy',
'fri-end': 'buddy',
'frnd': 'friend',
'frzn': 'freezing',
'fs': 'for sale',
'fsr': 'for some reason',
'ftbl': 'football',
'ftbomh': 'from the bottom of my heart',
'ftc': 'failure to communicate',
'ftw': 'for the win',
'fu': 'follow up',
'fu2': 'fuck you too',
'fub': 'fat ugly bastard',
'fuhgedaboudit': 'forget about it',
'fumf': 'fat ugly mother fucker',
'fw': 'foreign worker',
'fwb': 'friends with benefits',
'fwd': 'forward',
'fwm': 'fuck with me',
'fya': 'for your amusement',
'fyc': 'for your consideration',
'fyeo': 'for your eyes only',
'fyf': 'from your friend',
'fyi': 'for your information',
'g1': 'good one',
'g2g': 'got to go',
'g4i': 'go for it',
'g4n': 'good for nothing',
'g9': 'genius',
'gab': 'getting a beer',
'gad': 'go and die',
'gafl': 'get a fucking life',
'gafyk': 'get away from your keyboard',
'gal': 'girl',
'gap': 'got a pic?',
'gas': 'got a second?',
'gawd': 'god',
'gbtw': 'get back to work',
'gcp': 'golden cheese pie',
'gd': 'good',
'gdi': 'god damn it',
'geelo': 'zero',
'gf': 'girlfriend',
'gfi': 'go for it',
'gfn': 'good for nothing',
'gfon': 'good for one night',
'gfs': 'gao fu shuai',
'gftd': 'gone for the day',
'gfy': 'go fuck yourself',
'ggdd': 'gong gong dai dai',
'ggn': 'gotta go now',
'ggoh': 'gotta get out of here',
'ggy': 'go google yourself',
'ghm': 'god help me',
'gi': 'google it',
'gilf': 'grandmother I would like to fuck',
'giybf': 'google is your best friend',
'gla': 'good luck all',
'glawd': 'good luck and well done',
'glb': 'good looking boy',
'glbt': 'gay, lesbian, bisexual, transgender',
'glg': 'good looking girl',
'glgh': 'good luck and good hunting',
'glgt': 'got link for talk',
'glhf': 'good luck have fun',
'gm': 'good morning',
'gmab': 'give me a break',
'gmily': 'good morning I love you',
'gmta': 'great minds think alike',
'gn': 'good night',
'gn8': 'good night',
'gns': 'gangnam style',
'gnsd': 'good night sweet dreams',
'gob': 'game on bitches',
'goi': 'get over it',
'gok': 'god only knows',
'gonna': 'going to',
'gov': 'government',
'govn': 'government',
'govt': 'government',
'gpgt': 'got picture got talk',
'gr8': 'great',
'gratz': 'congratulations',
'grrl': 'girl',
'grrlz': 'girls',
'gso': 'girls supply officer',
'gsoh': 'good sense of humor',
'gt': 'good try',
'gtfo': 'get the fuck out',
'gtfooh': 'get the fuck out of here',
'gtg': 'got to go',
'gtgb': 'got to go bye',
'gth': 'go to hell',
'gtk': 'good to know',
'gtsy': 'glad to see you',
'gud': 'good',
'gud v gud': 'good very good',
'gunna': 'going to',
'gvg': 'good very good',
'gvgt': 'got video got talk',
'gws': 'get well soon',
'gx': 'gong xi',
'gxfc': 'gong xi fa cai',
'h&k': 'hugs and kisses',
'h/o': 'hold on',
'h/p': 'hold please',
'h2cus': 'hope to see you soon',
'h2s': 'here to stay',
'h4u': 'hot for you',
'h4xx0r': 'hacker',
'h8': 'hate',
'h81': 'hotel 81',
'h9': 'husband',
'haf': 'have',
'hag1': 'have a good one',
'hagd': 'have a great day',
'hagn': 'have a good night',
'hago': 'have a good one',
'hak': 'hugs and kisses',
'hand': 'have a nice day',
'har': 'hit and run',
'hav': 'have',
'hay': 'how are you',
'hb': 'happy birthday',
'hbd': 'happy birthday',
'hbu': 'how bout you',
'hby': 'hell bitch yes',
'hcny': 'happy chinese new year',
'hfu': 'hot for you',
'hi5': 'high five',
'hifw': 'how I felt when',
'hig': "how's it going?",
'himbo': 'male bimbo',
'hl': 'hao lian',
'hld': 'hold',
'hlg': 'hilang',
'hll': 'halal',
'hlny': 'happy lunar new year',
'hmmm zai': "don't know",
'hmv': 'home made video',
'hny': 'happy new year',
'ho': 'hold on',
'hokay': 'ok',
'howru': 'how are you',
'hp': 'hold please',
'hpy': 'happy',
'hrcn': 'hurricane',
'hrm': 'haram',
'hsik': 'how should I know',
'hsl': 'hum sup lou',
'hth': 'hope this helps',
'hts': 'here to stay',
'hu': 'hook up',
'huai': 'why',
'huat': 'what',
'hud': 'how you doing?',
'hugz': 'hugs',
'hungreh': 'hungry',
'huya': 'head up your ass',
'hv': 'have',
'hw cn': 'how can',
'hwga': 'here we go again',
'hwk': 'hawker',
'hx': 'history or hospital',
'hyd': 'how you doing?',
'i<3i': 'i love it',
'i<3u': 'i love you',
'iat': 'i am tired',
'iaw': 'i agree with',
'iaym': 'i am your master',
'ibk': 'idiot behind keyboard',
'ibrb': "i'll be right back",
'icbw': 'i could be wrong',
'iccl': "i couldn't care less",
'icw': "i can't wait",
'icwum': 'i see what you mean',
'icwym': 'i see what you mean',
'icymi': 'in case you missed it',
'id': 'identification',
'id10t': 'idiot',
'idc': "I don't care",
'idgad': "i don't give a damn",
'idgaf': "i don't give a fuck",
'idk': "I don't know",
'idky': "i don't know you",
'idl': 'ideal',
'idm': "it doesn't matter",
'idrk': "i don't really know",
'idts': "i don't think so",
'idw': "I don't want",
'ig': 'instagram',
'ih8it': 'i hate it',
'ihnc': 'i have no clue',
'ihno': 'i have no opinion',
'iirc': 'if I remember correctly',
'ijs': "i'm just saying",
'ikr': 'i know, right?',
'ikwym': 'i know what you mean',
'ili': 'i love it',
'ilu': 'i love you',
'ily': 'i love you',
'ily2': 'i like you too',
'ilysm': 'i love you so much',
'im': 'instant messaging',
'imba': 'imbalanced',
'imco': 'in my considered opinion',
'ime': 'in my experience',
'imezru': 'i am easy, are you?',
'imho': 'in my humble opinion',
'imi': 'i mean it',
'imjs': 'i am just saying',
'iml': 'i am laughing',
'imma': "i'm gonna",
'immelly': 'immediately',
'imml': 'i make myself laugh',
'imo': 'in my opinion',
'impov': 'in my point of view',
'imr': 'i mean really',
'imru': 'i am, are you?',
'ims': 'i am sorry',
'imu': 'i miss you',
'imy': 'i miss you',
'inbd': "it's no big deal",
'inmp': "it's not my problem",
'innards': 'in other words',
'inpo': 'in no particular order',
'insta': 'instagram',
'ioh': "i'm outta here",
'iot': 'in order to',
'iou': 'i owe you',
'ir8': 'i rate',
'irc': 'if remember correctly',
'irl': 'in real life',
'irstbo': 'it really sucks the big one',
'ish': 'is',
'isit': 'is it',
'issit': 'is it',
'istm': 'it seems to me',
'ita': 'i totally agree',
'itmt': 'in the meantime',
'its a d8': "it's a date",
'ium': 'if you must',
'iwalu': 'i will always love you',
'iwaly': 'i will always love you',
'iwu': 'i want you',
'iyd': 'in your dreams',
'iydmma': "if you don't mind my asking",
'iykwim': 'if you know what I mean',
'iyo': 'in your opinion',
'izit': 'is it',
'izzit': 'is it',
'j/j': 'just joking',
'j/k': 'just kidding',
'j/o': 'jerking off',
'j/p': 'just playing',
'j/w': 'just wondering',
'j2luk': 'just to let you know',
'j2lyk': 'just to let you know',
'j4f': 'just for fun',
'j4g': 'just for grins',
'j4t': 'just for today',
'j5m': 'just five minutes',
'jad': 'just another day',
'jam': 'just a minute',
'jas': 'just a second',
'jdi': 'just do it',
'jdmj': 'just doing my job',
'jealz': 'jealous',
'jellz': 'jealous',
'jfc': 'jesus fucking christ',
'jff': 'just for fun',
'jfg': 'just for grins',
'jfi': 'just for information',
'jft': 'just for today',
'jgn': 'do not',
'jgn catastrophe': 'jangan catastrophe',
'jgn tension': 'relax',
'jheelo': 'zero',
'jibra': 'zebra',
'jic': 'just in case',
'jj': 'just joking',
'jk': 'just kidding',
'jlb': 'useless person',
'jlmk': 'just let me know',
'jln': 'walk',
'jln jln': 'walk around',
'jm2c': 'just my two cents',
'jmo': 'just my opinion',
'jo': 'jerking off',
'jp': 'just playing',
'js': 'eat shit',
'jsu': 'just shut up',
'jsyk': 'just so you know',
'jt': 'just teasing',
'jtluk': 'just to let you know',
'jtlyk': 'just to let you know',
'jtol': 'just thinking out loud',
'jtou': 'just thinking of you',
'jtoy': 'just thinking of you',
'juil': 'just you I love',
'jw': 'just wondering',
'k': 'ok',
'k4y': 'kiss for you',
'kar pak': 'car park',
'kb': 'dick head',
'kbd': 'keyboard',
'kc trap': 'kum cheng trap',
'kcco': 'keep calm & carry on',
'kci': 'backside itcy',
'kcps': 'kan cheong pi sai',
'kcs': 'kan cheong spider',
'kdn': 'kidding',
'kena tgkp': 'kena tangkap',
'kewl': 'cool',
'kfy': 'kiss for you',
'khyf': 'know how you feel',
'kiddin': 'kidding',
'kidin': 'kidding',
'kir': 'keep it real',
'kiss': 'keep it simple stupid',
'kit': 'keep in touch',
'kity': 'keep it to yourself',
'kiv': 'keep in view',
'kjw': 'kong jiao wei',
'kk': 'ok',
'kkb': 'penis',
'kkj': 'penis',
'kklp': 'kah kana lum par',
'kkylp': 'kiao kar yo lum par',
'kl': 'kuai lan',
'klk': 'kuai lan kia',
'klkk': 'kia lai kia ker',
'kma': 'kiss my ass',
'kmn': 'kill me now',
'kmp': 'keep me posted',
'kmsl': 'killing myself laughing',
'kns': 'kana sai',
'knw': 'know',
'kotc': 'kiss on the cheek',
'kotl': 'kiss on the lips',
'kp': 'kao peh',
'kpc': 'keeping parents clueless',
'kpkb': 'complained',
'kpo': 'kaypoh',
'kpo chee': 'kaypoh chee',
'kpo kia': 'kaypoh kia',
'krone': 'clone account',
'ksl': 'kia si lang',
'kthxbye': 'ok thanks bye',
'ktt': 'kim tang tang',
'kty': 'keep to yourself',
'kwim': 'know what I mean?',
'kyfc': 'keep your fingers crossed',
'kym': 'ke yi ma',
'kys': 'kill yourself',
'kysoti': 'keep your stick on the ice',
'l&r': 'love and respect',
'l/m': 'left message',
'l2m': 'listening to music',
'l3l2': 'l-cube l-square',
'l5': 'lu lai lu lau lan',
'l8': 'late',
'l8r': 'later',
'l?^': "let's hook up",
'l@u': 'laughing at you',
'lafs': 'love at first sight',
'lame': 'being ridiculous',
'laoj': 'laughing at own joke',
'larp': 'live action role playing',
'larper': 'live action role player',
'larping': 'live action role playing',
'lau': 'laughing about you',
'lawl': 'laughing out loud',
'laydee': 'lady',
'lbh': "let's be honest",
'lbs': 'laughing but serious',
'lbvs': 'laughing but very serious',
'lcb': 'old woman',
'lcly': 'lan si lan yong',
'ldr': 'long distance relationship',
'lebber': 'level',
'lemme': 'let me',
'lenglish': 'english spoken in Klang Malaysia',
'lep': 'love emo people',
'letem': 'let them',
'lf': "let's fuck",
'lftd': 'laugh for the day',
'lh': 'laughing hysterically',
'lh6': 'let’s have sex',
'lhd': 'left hand drive',
'lhk': 'love hugs kisses',
'lhl': 'lee hsien loong',
'lho': 'laughing head off',
'lhos': 'lets have online sex',
'lhso': "let's have sex online",
'lhu': "let's hook up",
'lib': 'lying in bed',
'liddat': 'like that',
'lifo': 'last in, first out',
'lil': 'little',
'lir': 'let it rest',
'lis': 'laughing in silence',
'lj': 'lan jiao',
'lj face': 'lan jiao face',
'ljb': 'lan jiao bin',
'ljbf': "let's just be friends",
'ljw': 'lan jiao wei',
'lk': 'like',
'lkk': 'very old',
'lky': 'lee kuan yew',
'llello': 'cocaine',
'lllll': 'lu lai lu lau lan',
'llpof': 'liar liar pants on fire',
'lls': 'laughing like shit',
'llst': 'nothing can be done just accept it',
'lm': 'left message',
'lm46': "let's meet for sex",
'lm4a~##zzzz>': "let's meet for a joint",
'lmao': 'laughing my ass off',
'lmbao': 'laughing my black ass off',
'lmbpo': 'laughing my booty pop off',
'lmfao': 'laughing my fucking ass off',
'lmho': 'laughing my head off',
'lmirl': "let's meet in real life",
'lmk': 'let me know',
'lms': 'like my status',
'lny': 'lunar new year',
'loanmai': "If you don't mind",
'lob': 'lying on bed',
'lok': 'lots of kisses',
'lol': 'laughing out loud',
'lola': 'laugh out loud again',
'lolion': 'lol+lion',
'lolol': 'lots of laugh out louds',
'lolpmp': 'laugh out loud peed my pants',
'lolrotf&icgu': "laughing out loud rolling on the floor & I can't get up",
'lols': 'laughing out loud',
'lolx': 'laughing out loud',
'lolz': 'laughing out loud',
'lombard': 'lots of money but a right dick',
'loml': 'love of my life',
'lonh': 'lights on, nobody home',
'lool': 'laughing outrageously out loud',
'loomm': 'laughing out of my mind',
'lou': 'laughing over you',
'lpk': 'lepak',
'lpk one corner': 'relax in one corner',
'lpos': 'lazy piece of shit',
'lppl': 'caught in both directions',
'lss': 'long story short',
'lsv': 'language, sex, violence',
'ltd': 'lovers till death',
'ltic': 'laughing till I cry',
'ltio': 'laughing till I orgasm',
'ltm': 'laughing to myself',
'ltns': 'long time no see',
'ltr': 'long term relationship',
'lts': 'laughing to self',
'lugls': 'love you guys like sisters',
'luk': 'luck',
'lul': 'laughing out loud',
'lulz': 'laughing out loud',
'lum': 'love you man',
'lumu': 'love you miss you',
'lumumi': 'love you miss you mean it',
'luser': 'loser',
'lusm': 'love you so much',
'luv': 'love',
'lvl': 'level',
'lwl': 'lee wei ling',
'lwu': 'laughing with you',
'lwy': 'laughing with you',
'ly': 'love you',
'ly4e': 'love you forever',
'lya': 'love you all',
'lyb': 'love you babe',
'lycylbb': 'love you, see you later, bye bye',
'lykyamy': 'love you, kiss you, already miss you',
'lyl': 'love you lots',
'lylab': 'love you like a brother',
'lylas': 'love you like a sister',
'lylb': 'love you later bye',
'lymi': 'love you, mean it',
'lymy': 'love you miss you',
'lymymi': 'love you miss you mean it',
'lysm': 'love you so much',
'lysyb': 'love ya, see ya, bye',
'lywamh': 'love you with all my heart',
'm': 'male',
'm02': 'my two cents',
'm2': 'me too',
'm4c': 'meet for coffee',
'm4m': 'men seeking men',
'm8': 'mate',
'ma': 'mature audience',
'macnoner': 'mcdonalds',
'manglish': 'english spoken in Malaysia',
'mat rmpt': 'street racer',
'mb': 'message board',
'mbn': 'must be nice',
'mc': 'merry christmas',
'mcc': 'muddleheaded',
'mcm': 'man crush monday',
'meh': 'whatever',
'mehnoner': 'mcdonalds',
'mejr': 'my eyes just rolled',
'mf': 'my friend',
'mfrc': 'my fingers are crossed',
'mfwic': "mother fucker who's in charge",
'mhbfy': 'my heart bleeds for you',
'mhbp': 'mai hiam buay pai',
'mhhmuh': 'yes',
'mhoty': "my hat's off to you",
'mhyf': 'move how you feel',
'mia': 'missing in action',
'mid-life xtc': 'mid-life ecstasy',
'mih': 'make it happen',
'mihap': 'may I have your attention please',
'mil': 'mother-in-law',
'milf': "mother i'd like to fuck",
'min': 'minutes',
'minah rmpt': 'minah rempit',
'mins': 'minutes',
'mirl': 'meet in real life',
'mish': 'miss',
'mishu': 'miss you',
'mistweet': 'tweet mistake',
'mitin': 'more info than I needed',
'miw': 'men in white PAP',
'mklghlg': 'mai ka li gong hor li gian',
'mkltws': 'meng kia long tio wu siah',
'mkn': 'eat',
'mkn session': 'eating session',
'mkop': 'my kind of place',
'mlas': 'my lips are sealed',
'mlia': 'my life is average',
'mlmlwm': 'I do not want',
'mls': 'lazy',
'mmg': 'memang',
'mmha2u': 'my most humble apologies to you',
'mmk': 'umm, ok',
'mml': 'made me laugh',
'mmt': 'mou man tai',
'mmyt': 'mail me your thoughts',
'mob': 'mobile',
'mofo': 'mother fucker',
'moi': 'my or me',
'motd': 'message of the day',
'mrpk': 'merepek',
'mrt': 'modified retweet',
'msg': 'message',
'msmd': 'monkey see monkey do',
'msta': 'must see to appreciate',
'mstm': 'makes sense to me',
'mt': 'modified tweet',
'mtf': 'more to follow',
'mtfbwy': 'may the force be with you',
'mtla': 'my true love always',
'mua': 'kisses',
'muah': 'kisses',
'mum': 'merge using moments',
'musm': 'miss you so much',
'mva': 'motor vehicle accident',
'mwa': 'kisses',
'mwah': 'kisses',
'mwahugz': 'kisses and hugs',
'myl': 'mind your language',
'myob': 'mind your own business',
'mysm': 'miss you so much',
'mysp': 'myspace',
'myt': 'meet you there',
'n/a': 'not applicable',
'n/m': 'nothing much',
'n/t': 'no text',
'n00b': 'newbie',
'n1': 'nice one',
'n2m': 'not to mention',
'na': 'not applicable',
'nadt': 'not a damn thing',
'nagi': 'not a good idea',
'nah': 'no',
'nato': 'no action, talk only',
'naz': 'name, address, zip',
'nb4t': 'not before time',
'nbab': 'not beng act beng',
'nbd': 'no big deal',
'nbfab': 'not bad for a beginner',
'nblfy': 'nothing but love for you',
'nbnbnlm': 'no boobies no beauty nobody love me',
'nbs': 'no bull shit',
'ncac': 'not cool act cool',
'ne': 'any',
'ne-wayz': 'anyways',
'ne1': 'anyone',
'ne1er': 'anyone here?',
'ne2h': 'need to have',
'nekkid': 'naked',
'netizen': 'user of the Internet',
'newbie': 'beginner',
'news': 'north, east, west, south',
'nfe': 'no fucking excuses',
'nff': 'no fucking fair',
'nfg': 'not fucking good',
'nfi': 'no fucking idea',
'nfw': 'no fucking way',
'ng': 'new game',
'ngh': 'not gonna happen',
'ngl': 'not gonna lie',
'nhah': 'not handsome act handsome',
'nhnt': 'no head no tail',
'ni': 'not interested',
'nite': 'tonight',
'njapf': 'not just another pretty face',
'njhl': 'envious',
'nlal': 'not lian act lian',
'nlnt': 'no link no talk',
'nlt': 'no later than',
'nme': 'enemy',
'nmh': 'not much here',
'nmnhnlm': 'no money no honey nobody love me',
'nmp': 'not my problem',
'nmp3nt': 'no mp3 no talk',
'nmte': 'now more than ever',
'nmu': 'not much, you',
'nn': 'neh neh',
'nnan': 'not nice act nice',
'nnp': 'neh neh pok',
'no0blet': 'beginner',
'no1': 'no one',
'no gov': 'no government',
'no govn': 'no government',
'no govt': 'no government',
'noa': 'not online anymore',
'nobmr': 'none of my business, right',
'nofi': 'no offence intended',
'nomb': 'none of my business',
'noob': 'beginner',
'nope': 'no',
'nor chat': 'not yet',
'nowsaday': 'nowadays',
'noy': 'not online yet',
'noyb': 'none of your business',
'np': 'no problem',
'npap': 'not pretty act pretty',
'nphtt': 'no discussion without proof',
'npjtt': 'talk without proof',
'npnt': 'no discussion without proof',
'nqa': 'no questions asked',
'nrar': 'not rich act rich',
'nrg': 'energy',
'nrn': 'no reply necessary',
'nsas': 'not smart act smart',
'nsb': 'not sure but',
'nsf': 'national service man',
'nsmen': 'national service man',
'nsnp': 'no sound no picture',
'nta': 'not this again',
'ntat': 'not tall act tall',
'ntbn': 'no text back needed',
'nth': 'nothing',
'ntim': 'not that it matters',
'ntimm': 'not that it matters much',
'ntk': 'nice to know',
'ntm': 'not that much',
'ntmu': 'nice to meet you',
'ntmy': 'nice to meet you',
'nts': 'note to self',
'ntw': 'not to worry',
'ntymi': 'now that you mention it',
'nub': 'beginner',
'nuff': 'enough',
'nvm': 'never mind',
'nvr': 'never',
'nw': 'no way',
'nwal': 'nerd without a life',
'nwmant': 'no wma no talk',
'nwr': 'not work related',
'ny': 'new year',
'o$p$': 'owe money pay money',
'oatus': 'on a totally unrelated subject',
'oaus': 'on an unrelated subject',
'ob': 'out of bounds',
'ob marker': 'out of bounds marker',
'obcc': 'off beat cha cha',
'obv': 'obviously',
'oc': 'original character',
'ocb': 'female masturbation',
'ocd': 'obsessive compulsive disorder',
'ofc': 'of course',
'og': 'original gangster',
'oh': 'overheard',
'oic': 'oh, I see',
'oicu812': 'oh I see, you ate one too',
'oirwis': 'oh I remember what I said',
'okt': 'pimp',
'ol': 'office lady',
'oleng joo': 'orange juice',
'oll': 'online love',
'oln': 'online netiquette',
'olo': 'only laughed once',
'oltl': 'one life to live',
'om': 'old man',
'omb': 'oh my buddha',
'omdb': 'over my dead body',
'ome': 'oh my edward',
'omfg': 'oh my fucking god',
'omg': 'oh my god',
'omgd': 'oh my gosh, duh',
'omgwtfbbq': 'oh my god what the fuck barbeque',
'oml': 'oh my lord',
'omma': 'oh my aching ass',
'omt': 'oh my tian',
'omw': 'on my way',
'omwt': 'on my way too',
'onid': "oh no I didn't",
'onny': 'only',
'ons': 'one night stand',
'onud': "oh no you didn't",
'onyd': "oh no you didn't",
'ooak': 'one of a kind',
'oof': 'out of facility',
'ooh': 'out of here',
'ooi': 'out of interest',
'oomf': 'one of my followers',
'oot': 'out of touch',
'ootb': 'out of the blue',
'ootd': 'outfit of the day',
'orbi gd': 'you deserved it',
'orbi gud': 'you deserved it',
'oreddy': 'already',
'orh': 'oh I see',
'os': 'outstation',
'osif': 'oh shit I forgot',
'osintot': 'oh shit I never thought of that',
'oso': 'also',
'oso can': 'also can',
'ost': 'on second thought',
'otak u': 'otak you',
'otb': 'on the ball',
'otc': 'over the counter',
'ote': 'over the edge',
'oth': 'off the hook',
'otl': 'out to lunch',
'otoh': 'on the other hand',
'otot': 'own time own target',
'otp': 'on the phone',
'otr': 'on the road',
'ots': 'on the scene',
'ott': 'over the top',
'ottomh': 'off the top of my head',
'otw': 'on the way',
'ousu': 'oh you shut up',
'ov': 'over',
'ovr': 'over',
'ownd': 'owned',
'ownself': 'task performed alone',
'p&c': 'private and confidential',
'p/u': 'pick up',
'p2c2e': 'process too complicated too explain',
'parroting': 'copying the reply',
'paul lampard': 'brown nosing',
'paw': 'parents are watching',
'pax': 'passengers',
'pbg': 'fat boy behaviour',
'pbiab': 'pay back is a bitch',
'pblm': 'problem',
'pbuh': 'peace be upon him',
'pc': 'personal computer',
'pc4pc': 'picture comment for picture comment',
'pcb': 'phua chee bye',
'pcc': 'male masturbation',
'pcm': 'please call me',
'pcn': 'pui chao nuah',
'pcw': 'post count warrior',
'pd': 'public domain',
'pda': 'public display of affection',
'pdf': 'pedophile',
'pdh': 'pretty darn hot',
'pdmm': 'foreign mother accompanying child',
'pds': "please don't shout",
'peeps': 'people',
'perbird': 'pervert',
'pgo': 'police general orders',
'pic': 'picture',
'pics': 'picture',
'pimpl': 'peeing in my pants laughing',
'pio': 'pass it on',
'pir': 'parent in room',
'pix': 'pics',
'pkl': 'cover everything',
'pkm': 'pukimak',
'pkt': 'packet',
'pl': 'bad person',
'pl0x': 'please',
'planking': 'to lie face down',
'plj': 'peace love joy',
'plp': 'brown nose',
'pls': 'please',
'plu': 'people like us',
'plur': 'peace, love, unity, respect',
'plz': 'please',
'pm': 'private message',
'pmki': 'pretty much killing it',
'pml': 'pissed myself laughing',
'pmp': 'peeing my pants',
'pmsl': 'pissed my self laughing',
'po': 'piss off',
'poak': 'passed out at keyboard',
'pos': 'piece of shit',
'poser': 'pretender',
'potb': 'pat on the back',
'potd': 'photo of the day',
'pov': 'point of view',
'pp': 'personal problem',
'ppk': 'stand someone up',
'ppl': 'people',
'ppr': 'paper',
'prawn': 'porn',
'prc': "People's Republic of China",
'prembry': 'primary',
'pro': 'professional',
'prob': 'problem',
'prsn': 'perasan',
'prt': 'partial re-tweet',
'pruss satu': 'plus satu',
'pruss wan': 'plus one',
'ps king': 'pang seh king',
'ps queen': 'pang seh queen',
'psog': 'pure stroke of genius',
'ptfo': 'passed the fuck out',
'ptl': 'praise the lord',
'ptmm': 'please tell me more',
'pu': 'pick up',
'pvp': 'player versus player',
'pwd': 'Public Works Department',
'pwoms': 'parent watching over my shoulder',
'pza': 'pizza',
'qbs': 'qin bo sai',
'qc': 'quality control',
'qcb': 'arrogant woman',
'qfbk': 'quote for bun knife',
'qft': 'quoted for truth',
'ql': 'quit laughing',
'qotd': 'quote of the day',
'qq': 'quick question',
'qs': 'quit scrolling',
'qt': 'cutie',
'qtp': 'qia tar por',
'r u thr?': 'are you there',
'r&d': 'research and development',
'r&r': 'rest and relaxation',
'r8': 'rate',
'r u da?': 'are you there',
'r u goin?': 'are you going',
'rabz': 'rabakz',
'raebnc': 'read and enjoyed, but no comment',
'raf': 'random as fuck',
'rafo': 'read and find out',
'ratm': 'rage against the machine',
'rb@ya': 'right back at ya',
'rbay': 'right back at you',
'rbtl': 'read between the lines',
'rbu': 'rainbows, butterflies, unicorns',
'rc': 'remote control',
'rcp': 'real cheese pie',
'rdf': 'real deal feeling',
're': 'reply',
'ready already': 'I am ready to go',
'red pkt': 'red packet',
'repeat again': 'repeat',
'reso': 'reservation',
'rf': 'red face',
'rfd': 'request for discussion',
'rfp': 'request for proposal',
'rgd': 'regards',
'ridic': 'ridiculous',
'rl': 'real life',
'rlco': 'real life conference',
'rlf': 'real life friend',
'rlrt': 'real life retweet',
'rlx': 'relax',
'rly': 'really',
'rm': 're-make',
'rmb': 'rings my bell',
'rmbr': 'remember',
'rmbt': 'rembat',
'rmma': 'reading my mind again',
'rmpt': 'rempit',
'rn': 'right now',
'rnn': 'reply not necessary',
'rny': 'rainy',
'ro': 'routine order',
'robert': 'radish',
'robert tao': 'radish',
'roc': 'relax one corner',
'rock': 'lock',
'rofl': 'rolling on floor laughing',
'roflmao': 'rolling on floor laughing my ass off',
'roflol': 'rolling on floor laughing out loud',
'rotf': 'rolling on the floor',
'rotfl': 'rolling on the floor laughing',
'rotflmao': 'rolling on the floor laughing my ass off',
'rotflmfao': 'rolling on the floor laughing my fucking ass off',
'rotflol': 'rolling on the floor laughing out loud',
'rotgl': 'rolling on the ground laughing',
'rotglmao': 'rolling on the ground laughing my ass off',
'rox': 'rocks',
'rpg': 'role playing games',
'rs': 'radish sister',
'rsm': 'regimental sergeant major',
'rt': 're-tweet',
'rtbs': 'reason to be single',
'rtfaq': 'read the frequently asked questions',
'rthx': 'retweet thanks',
'rtk': 'return to keyboard',
'ru': 'are you',
'ru/18': 'are you over 18?',
'ru 18': 'are you under 18?',
'rufkm': 'are you fucking kidding me?',
'ruh': 'are you horny?',
'rumorf': 'are you male or female?',
'ruok': 'are you ok?',
'rup': 'read up please',
'rus': 'are you serious?',
'rusos': 'are you sos?',
'rut': 'are you there',
'ryfm': 'read your friendly manual',
'ryo': 'roll your own',
'rys': 'read your screen',
"s'pore": 'singapore',
"s'porean": 'singporean',
's2r': 'send to receive',
's2u': 'same to you',
's4l': 'spam for life',
's4s': 'share for share',
's^': "what's up",
'sah rong party gal': 'Chinese woman who exclusively dates European man',
'sah rong party girl': 'Chinese woman who exclusively dates European man',
'sah rong party gurl': 'Chinese woman who exclusively dates European man',
'sahd': 'stay-at-home dad',
'sahm': 'stay at home mom',
'sahp': 'stay-at-home parent',
'sarong party gal': 'Chinese woman who exclusively dates European man',
'sarong party gurl': 'Chinese woman who exclusively dates European man',
'sarung party gal': 'Chinese woman who exclusively dates European man',
'sarung party girl': 'Chinese woman who exclusively dates European man',
'sarung party gurl': 'Chinese woman who exclusively dates European man',
'sbf': 'sammyboy forum',
'sbt': "sorry 'bout that",
'sc': 'stay cool',
'scnr': 'sorry, could not resist',
'scuse': 'excuse',
'sd': 'sweet dreams',
'sdd': 'siao ding dong',
'sec': 'second',
'sed': 'said enough darling',
'seg': 'shit eating grin',
'self-pwn': 'self-own',
'selfie': 'picture of yourself',
'seltering': 'to stick out your rear in a fitness pose',
'semen mixture': 'cement mixer',
'sep': "somebody else's problem",
'sete': 'smiling ear to ear',
'sexciting': 'exciting',
'sexperience': 'experience',
'sexpert': 'expert',
'sexpose': 'expose',
'sexting': 'text messages with sexual content',
'sff': 'so freaking funny',
'sfw': 'safe for work',
'sg': 'shuai ge',
'sgtm': 'sounds good to me',
'sh': 'shit happens',
'shb': 'should have been',
'shelfie': 'picture of objects arranged on a shelf',
'shhh': 'quiet',
'shld': 'should',
'shoulda': 'should have',
'sia': 'say it again',
'sign xtra': 'sign extra',
'sil': 'sister-in-law',
'singlest': 'single',
'sis': 'sister',
'sista': 'sister',
'sit': 'stay in touch',
'sitd': 'still in the dark',
'situbi': 'say it till you believe it',
'siy': 'search inside yourself',
'sjp': 'sian jit pua',
'sk': 'sai kang',
'sk8er': 'skater',
'sk8r': 'skater',
'sk warrior': 'sai kang warrior',
'sknkr': 'skin care',
'slap': 'sounds like a plan',
'slc': 'shake leg company',
'slh': 'salah',
'slh parking': 'salah parking',
'slm': 'socially limiting maneuver',
'slt': 'something like that',
'sm': 'senior moment',
'sm1': 'someone',
'smelly': 'smiley',
'smem': 'send me e-mail',
'smf': 'so much fun',
'smfh': 'shaking my fucking head',
'smh': 'shaking my head',
'smim': 'send me an instant message',
'sml': 'what the fuck',
'smlj': 'what the fuck',
'sms': 'short message service',
'smsed': 'short message service',
'smsing': 'short message service',
'smt': 'something',
'smtc': 'what is the issue?',
'smth': 'something',
'smtj': 'what is the issue?',
'snl': 'same night lay',
'snny': 'sunny',
'soab': 'son of a bitch',
'sob': 'son of a bitch',
'soe': 'start of exams',
'sofa king': 'so fucking',
'soh': 'sense of humor',
'some1': 'someone',
'sori': 'sorry',
'sori no cure': 'sorry no cure',
'sosad': 'same old song and dance',
'sot': 'short on time',
'spg': 'sarong party girl',
'spk': 'speak',
'spoof': 'spoof thread',
'spoopy': 'scary and funny',
'sppp': 'steady pom pee pee',
'spst': 'same place same time',
'sq': 'excuse me',
'srs': 'serious',
'srsly': 'seriously',
'sry': 'sorry',
'ssdd': 'same shit different day',
'ssll': 'looking around',
'ssrr': 'looking around',
'stbx': 'soon to be ex',
'stby': 'sucks to be you',
'std': 'sexually transmitted disease',
'step bz': 'step busy',
'step gd': 'step good',
'step gud': 'step good',
'stewpig': 'stupid',
'stfu': 'shut the fuck up',
'stfw': 'search the fucking web',
'sth': 'something',
'sthu': 'shut the hell up',
'stm': 'spank the monkey',
'stml': 'short term memory loss',
'stoked': 'very happy, excited',
'stomper': 'someone who posts frequently on STOMP',
'stp': 'crazy guy',
'str8': 'straight',
'stw': 'search the web',
'stys': 'speak to you soon',
'su': 'shut up',
'sub': 'shut up bitch',
'sup': "what's up",
'sux': 'sucks',
'suyf': 'shut up you fool',
'swag': "boasting about one's skills",
'swalk': 'sealed with a loving kiss',
'swammie': 'firearm',
'swdyt': 'so what do you think?',
'sweet<3': 'sweetheart',
'swh': 'super white horse',
'swu': "so what's up",
'syk': 'so you know',
'syl': 'see you later',
'sys': 'see you soon',
't&c': 'terms and conditions',
't+': 'think positive',
't2go': 'time to go',
't2ul': 'talk to you later',
't2ut': 'talk to you tomorrow',
't@yl': 'talk at you later',
'ta': 'thanks again',
'tac': "that ain't cool",
'taf club': 'Trim and fit club',
'tafn': "that's all for now",
'tam': 'thanks a million',
'tanj': "there ain't no justice",
'tanstaafl': "there ain't no such thing as a free lunch",
'tap': 'take a pill',
'tarfu': 'things are really fucked up',
'tas': 'taking a shower',
'taw': 'teachers are watching',
'tay': 'thinking about you',
'tayn': 'thinking about you now',
'tba': 'to be advised',
'tbd': 'to be determined',
'tbh': 'to be honest',
'tbr': 'to be read',
'tbt': 'throwback thursday',
'tbu': 'thinking bout you',
'tby': "thinking 'bout you",
'tc': 'take care',
'tcob': 'taking care of business',
'tcoy': 'take care of yourself',
'tcp': 'thread chauvinist pig',
'tcss': 'talk cock sing song',
'tdtm': 'talk dirty to me',
'tdy': 'today',
'ten-penis': 'Tampines',
'text': 'text',
'tf': 'the fuck',
'tff': 'twitter follower-friend',
'tflms': 'thanks for letting me share',
'tfta': 'thanks for the add',
'tftu': 'thanks for the update',
'tfx': 'traffic',
'tgal': 'think globally, act locally',
'tgff': 'thank god for fridays',
'tggtg': 'that person has got to go',
'tgif': "thank god it's friday",
'tgkp': 'tangkap',
'tgkp emo': 'tangkap emo',
'tgkp feel': 'tangkap feel',
'tgkp jiwang': 'tangkap jiwang',
'thankz': 'thanks',
'thks': 'thanks',
'thn': 'then',
'thnks': 'thanks',
'thnx': 'thanks',
'tho': 'though',
'thotful': 'thoughtful',
'thrs': 'thursday',
'thru': 'through',
'thx': 'thanks',
'tia': 'thanks in advance',
'tiail': 'think I am in love',
'til': 'today I learned',
'tinwis': 'that is not what I said',
'tisc': 'this is so cool',
'tisl': 'this is so lame',
'tisnc': 'this is so not cool',
'tisnf': 'that is so not fair',
'tisnt': 'that is so not true',
'titf': 'that is too funny',
'tk jln': 'tak jalan',
'tkk': 'tan ku ku',
'tkp': 'tiko pek',
'tku4uk': 'thank you for your kindness',
'tl': 'time line',
'tl;dr': "too long; didn't read",
'tlc': 'tender loving care',
'tldr': "too long; didn't read",
'tlg': 'tolong',
'tlg lah': 'tolong lah',
'tlg skt': 'tolong sikit',
'tlgo': 'the list goes on',
'tlitbc': "that's life in the big city",
'tm': 'trust me',
'tmai': 'tell me about it',
'tmalss': 'to make a long story short',
'tmd': 'tamade',
'tmdf': 'to my dearest friend',
'tmft': 'too much free time',
'tmg': "that's my girl",
'tmi': 'too much information',
'tmm': 'tian mi mi',
'tmr': 'tomorrow',
'tmsgo': 'too much shit going on',
'tna': 'temporarily not available',
'tnt': 'till next time',
'tntl': 'trying not to laugh',
'tnx': 'thanks',
'tobg': 'this oughta be good',
'toh': 'the other half',
'tok': 'talk',
'tom': 'tomorrow',
'toon': 'cartoon',
'topca': 'till our paths cross again',
'tot': 'thought',
'totes': 'totally',
'tpk': 'tua pek kong',
'tpm': 'tweets per minute',
'tpt': 'trailer park trash',
'tqvm': 'thank you very much',
'trdmc': 'tears running down my cheeks',
'trndo': 'tornado',
'troo': 'true',
'trs': 'that really sucks',
'tru': 'through',
'tryna': 'trying to',
'ts': 'thread starter',
'tsb': 'tall, sexy, beautiful',
'tsia': 'this says it all',
'tsif': "thank science it's friday",
'tsnf': "that's so not fair",
'tstb': 'the sooner, the better',
'tta': 'tap that ass',
'ttbomk': 'to the best of my knowledge',
'ttg': 'time to go',
'ttiot': 'the truth is out there',
'ttksf': 'trying to keep a straight face',
'ttly': 'totally',
'ttm': 'to the max',
'tts': 'text to speech',
'ttth': 'ignored',
'tttt': 'these things take time',
'ttul': 'talk to you later',
'tty': 'talk to you',
'ttyawfn': 'talk to you a while from now',
'ttyiaf': 'talk to you in a few',
'ttyl': 'talk to you later',
'ttyl8r': 'talk to you later',
'ttyn': 'talk to you never',
'ttyob': 'tend to your own business',
'ttyootd': 'talk to you one of these days',
'ttys': 'talk to you soon',
'ttyt': 'talk to you tomorrow',
'tvm4yem': 'thanks very much for your e-mail',
'twaddict': 'twitter addict',
'twd': 'texting while driving',
'tweavesdropping': 'eavesdropping on twitter',
'tweeple': 'twitter people',
'tweeps': 'twitter peeps',
'tweet': 'twitter post',
'tweetsult': 'insulting tweet',
'tweetup': 'twitter meetup',
'twewbie': 'twitter newbie',
'twhab': "this won't hurt a bit",
'twhe': 'the walls have ears',
'twhs': "that's what he said",
'twimc': 'to whom it may concern',
'twinsies': 'twins',
'twit': "that's what I thought",
'twita': "that's what i'm talking about",
'twollower': 'twitter follower',
'twsi': 'that was so ironic',
'twss': "that's what she said",
'twti': 'that was totally ironic',
'twtr': 'twitter',
'twu': "that's what's up",
'tx': 'thanks',
'txt': 'text',
'txt im': 'text instant message',
'ty': 'thank you',
'tyclo': 'turn your caps lock off',
'tyl': 'text you later',
'tyvm': 'thank you very much',
'tyvm4yem': 'thank you very much for your e-mail',
'u': 'you',
'u2': 'you too',
'u2u': 'up to you',
'u4e': 'yours forever',
'u8': 'you ate?',
'u up': 'you up?',
'udh82bme': "you'd hate to be me",
'udm': "you're the man",
'ufn': 'until further notice',
'ug2bk': "you've got to be kidding",
'ugc': 'user-generated content',
'ugh': 'disgusted',
'ugtr': 'you got that right',
'ulkgr8': 'you look great',
'ull': 'you will',
'unt': 'until next time',
'uok': 'you ok?',
'uome': 'you owe me',
'ur': 'your',
'ur2k': 'you are too kind',
'ur grandfather army': 'your grandfather army',
'ur grandfather rd': 'your grandfather road',
'urapita': 'you are a pain in the ass',
'ursai': 'you are such an idiot',
'urself': 'yourself',
'urtb': 'you are the best',
'urw': 'you are welcome',
'urws': 'you are wise',
'uryy4m': 'you are too wise for me',
'urz': 'yours',
'utfsb': 'use the fucking search button',
'utm': 'under table money',
'uw': "you're welcome",
'uwm': 'you want me',
'vacay': 'vacation',
'vbg': 'very big grin',
'vbmg': 'very big mischievous grin',
'vbs': 'very big smile',
'veg': 'very evil grin',
'vfm': 'value for money',
'vgn': 'vegetarian',
'vim': 'very important member',
'vip': 'very important person',
'viv': 'very important visitor',
'vlog': 'video blog',
'vlogger': 'video blogger',
'vm': 'voice mail',
'vpl': 'visible panty line',
'vsf': 'very sad face',
'vwd': 'very well done',
'vwp': 'very well played',
'w/': 'with',
'w/e': 'whatever',
'w/o': 'without',
'w2f': 'way too funny',
'w2g': 'way to go',
'w4m': 'women for men',
'w8': 'wait',
'w9': 'wife in the room',
'w@': 'what',
'wabi': 'what a bright idea',
'waboc': 'what a bunch of crap',
'waci': 'what a cool idea',
'wad': 'without a doubt',
'wadi': 'what a dumb idea',
'wadr': 'with all due respect',
'waef': 'when all else fails',
'wafb': 'what a fucking bitch',
'wafm': 'what a fucking mess',
'wai': 'what an idiot',
'wall of text': 'long text post',
'wan': 'want',
'wan2': 'want to',
'wanna': 'want to',
'wassup': "what's up",
'wat': 'what',
'wat c c': 'what see see',
'wat luk luk': 'what look look',
'wat speaking u': 'what speaking you',
'wat toking u': 'what talking you',
'wati': 'what a terrible idea',
'wawi': 'what a wonderful idea',
'wayd': 'what are you doing?',
'wayn': 'where are you now?',
'wb': 'welcome back',
'wbs': 'write back soon',
'wbu': 'what bout you?',
'wby': "what 'bout you?",
'wc': 'who cares',
'wca': 'who cares anyway',
'wckd': 'wicked',
'wcw': 'woman crush wednesday',
'wd': 'well done',
'wdr': 'with due respect',
'wdt': 'who does that?',
'wdym': 'what do you mean?',
'wdys': 'what did you say?',
'wdyt': 'what do you think?',
'weathermageddon': 'very bad weather',
'wefie': 'self taken group picture',
'weg': 'wicked evil grin',
'welkam': 'welcome',
'wen': 'when',
'wenla': "would not",
'wgt': 'where got time',
'wh': 'white horse',
'whr': 'where',
'whut': 'what',
'winternity': 'winter for eternity',
'witw': 'what in the world',
'wk': 'wa kao',
'yandao': 'handsome',
'wknd': 'weekend',
'wks': "won't kena sack",
'wll': 'wait long long',
'wlmirl': 'would like to meet in real life?',
'wlu': 'wicked, love you',
'wlu2': 'wicked, love you too',
'wly': 'we love you',
'wndy': 'windy',
'wob': 'waste of bandwidth',
'wom': 'word of mouth',
'wombat': 'waste of money, brains and time',
'wondaful': 'wonderful',
'wotam': 'waste of time and money',
'wrm': 'warm',
'wrt': 'with regards to',
'wru': 'where are you',
'wrud': 'what are you doing?',
'wrudatm': 'what are you doing at the moment?',
'ws^': "what's up",
'wt': 'what',
'wtdb': "what's the difference between",
'wtf': 'what the fuck',
'wtfh': 'what the fucking hell',
'wtfnf': 'what the fucking fuck',
'wtg': 'way to go',
'wth': 'what the hell',
'wthin': 'what the hell is next',
'wtmi': 'way too much information',
'wtv': 'whatever',
'wu': "what's up",
'wuf': 'where you from',
'wuwh': 'wish you were here',
'wuwhima': 'wish you were here in my arms',
'wuz': 'was',
'wuz4dina': "what's for dinner?",
'wv': 'with',
'www': 'world wide web',
'wwy': 'where were you?',
'wx': 'weather',
'wycm': 'will you call me?',
'wyd': 'what you doing?',
'wym': 'what do you mean?',
'wyp': "what's your problem?",
'wyrn': "what's your real name?",
'wys': 'whatever you say',
'wysiwyg': 'what you see is what you get',
'wyt': 'whatever you think',
'wytb': 'wish you the best',
'wyw': 'wish you well',
'wywh': 'wish you were here',
'xbf': 'ex-boyfriend',
'xcb': 'xiao cha bor',
'xcuse': 'excuse',
'xgf': 'ex-girlfriend',
'xi10': 'exciting',
'xln': 'xiao long nu',
'xlnt': 'excellent',
'xmas': 'christmas',
'xmm': 'xiao mei mei',
'xo': 'kiss and hug',
'xoxo': 'hugs and kisses',
'xoxoxox': 'hugs, kisses',
'xoxozzz': 'hugs and kisses and sweet dreams',
'xpert': 'expert',
'xqzt': 'exquisite',
'xtc': 'ecstasy',
'xtl': 'cross the line',
'xtp': 'xiao tar por',
'xtra': 'extra',
'xxcc': 'kiss, kiss, hug, hug',
'y nt': 'why not',
'y': 'why',
"y'all": 'you all',
'yall': 'you all',
'yap': 'yes',
'yawobt': 'yet another waste of bandwidth thread',
'ybs': "you'll be sorry",
'yby': 'yeah baby yeah',
'ycmu': 'you crack me up',
'yct': 'your comment to',
'ydi': 'you deserved it',
'ydkm': "you don't know me",
'yea': 'yes',
'yeah': 'yes',
'yeap': 'yes',
'yest': 'yesterday',
'yf': 'wife',
'ygbk': 'you gotta be kidding',
'ygg': 'you go girl',
'yglt': "you're gonna love this",
'ygtbk': "you've got to be kidding",
'ygtr': 'you got that right',
'yiu': 'yes, I understand',
'ykw': 'you know what?',
'ykwim': 'you know what I mean',
'ym': 'yahoo mail',
'ymak': 'you may already know',
'ymal': 'you might also like',
'ymbkm': 'you must be kidding me',
'yngbt': "you're not gonna believe this",
'ynk': 'you never know',
'yntynk': 'you never try, you never know',
'yolo': 'you only live once',
'yoyo': "you're on your own",
'yr': 'year',
'yrag': 'you are a geek',
'yrl': 'you are lame',
'ysan': "you're such a nerd",
'ysdiw8': 'why should I wait?',
'ysic': 'why should I care?',
'ysj': "you're so jealin",
'ysk': 'you should know',
'yst': 'yesterday',
'ysyd': 'yeah, sure you do',
'ytb': "you're the best",
'ytrnw': "yeah that's right, now what?",
'yttm': 'you talk too much',
'yvw': "you're very welcome",
'yw': "you're welcome",
'yyss': 'yeah yeah sure sure',
'yyssw': 'yeah yeah sure sure whatever',
'zg': 'zao geng',
'zmg': 'oh my god',
'zoh my god': 'oh my god',
'zomg': 'oh my god',
'zzz': 'sleeping, bored, tired'}
